### ISSUE TITLE
decodeAudio.go example not run

### ISSUE THREAD

**Issue by juvasquezg** [targodan/ffgopeg#4] opened 2017-03-09 22:25 UTC
Hi,

I use ffmpeg 3.1.7 and when I run decodeAudio.go example I get:

```bash
# gopkg.in/targodan/ffgopeg.v1/avutil
could not determine kind of name for C.AV_PIX_FMT_AYUV64BE
could not determine kind of name for C.AV_PIX_FMT_AYUV64LE
could not determine kind of name for C.AV_PIX_FMT_CUDA
could not determine kind of name for C.AV_PIX_FMT_D3D11VA_VLD
could not determine kind of name for C.AV_PIX_FMT_GBRAP10BE
could not determine kind of name for C.AV_PIX_FMT_GBRAP10LE
could not determine kind of name for C.AV_PIX_FMT_GBRAP12BE
could not determine kind of name for C.AV_PIX_FMT_GBRAP12LE
could not determine kind of name for C.AV_PIX_FMT_MMAL
could not determine kind of name for C.AV_PIX_FMT_P010BE
could not determine kind of name for C.AV_PIX_FMT_P010LE
could not determine kind of name for C.AV_PIX_FMT_VAAPI
could not determine kind of name for C.AV_PIX_FMT_VIDEOTOOLBOX
could not determine kind of name for C.AV_PIX_FMT_YUV440P10BE
could not determine kind of name for C.AV_PIX_FMT_YUV440P10LE
could not determine kind of name for C.AV_PIX_FMT_YUV440P12BE
could not determine kind of name for C.AV_PIX_FMT_YUV440P12LE
```

Thank you!

**Comment by targodan** [comment] 2017-03-11 10:00
Hello there,

I just configured travis to test 3.1.7 and it didn't show up any errors. *But* travis does not test the decodeAudio example yet. On my PC with ffmpeg version 3.2.4 I can't reproduce it. So while I set up a test VM could you please give me the following information:

- Output of `go version`
- Output of `ffmpeg -buildconf`
- How did you install ffgopeg? Via `go get -u gopkg.in/targodan/ffgopeg.v1`?
- What linux distro are you using?

**Update:**
At least on the develop branch travis now executes the examples. No errors though.

**Update 2:**
I set up an Archlinux VM with ffmpeg 3.1.7 and go1.8 still could not reproduce.

**Comment by juvasquezg** [comment] 2017-03-11 15:58
Hi,

I installed ffmpeg 3.2.2 and decodeAudio run well.

Thak you!!

**Comment by targodan** [comment] 2017-03-11 18:45
Alright then. I'll close this.

Hope you like the library. 😉

**Closed as completed by targodan** 2017-03-11 18:45 UTC
Labels: bug, could not reproduce

**Comment by juvasquezg** [comment] 2017-03-12 02:20
Great,

I try to run muxing and demuxing all in golang and when I found ffgopeg I was really happy.

Thank you!!
